project:
  type: website
  output-dir: docs

format:
  html:
    toc: true
    linkcolor: purple
    theme: zephyr

website:
  navbar:
    background: success
    search: true
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd
        text: Home
      - section: "Brasil"
        contents:
          - text: "@brasilsemaborto"
            url: docs/pages/brasilsemaborto.html
          - text: "@nikolas_dm"
            url: docs/pages/nikolas_dm.html
          - text: "@PastorMalafaia"
            url: docs/pages/pastormalafaia.html
      - section: "Colombia"
        contents:
          - text: "@UnidosxlaVidaCo"
            url: docs/pages/unidosxlavidaco.html
          - text: "@MariaFdaCabal"
            url: docs/pages/mariafdacabal.html
          - text: "@misionpaz_"
            url: docs/pages/misionpaz.html
      - section: "Ecuador"
        contents:
          - text: "@_FamiliaEcuador"
            url: docs/pages/familiaecuador.html
          - text: "@etorrescobo"
            url: docs/pages/etorrescobo.html
          - text: "@MamelaFialloFlo"
            url: docs/pages/mamelafialloflo.html
  repo-url: https://github.com/DataCritica/capir-transfronteriza2-2023
  repo-actions: [edit, issue]
