project:
  type: website
  output-dir: docs

format:
  html:
    toc: true
    linkcolor: purple
    theme: zephyr

website:
  navbar:
    background: success
    search: true
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd
        text: Home
      - section: "Brasil"
        contents:
          - text: "@brasilsemaborto"
            url: pages/brasilsemaborto.ipynb
          - text: "@nikolas_dm"
            url: pages/nikolas_dm.ipynb
          - text: "@PastorMalafaia"
            url: pages/pastormalafaia.ipynb
      - section: "Colombia"
        contents:
          - text: "@UnidosxlaVidaCo"
            url: pages/unidosxlavidaco.ipynb
          - text: "@MariaFdaCabal"
            url: pages/mariafdacabal.ipynb
          - text: "@misionpaz_"
            url: pages/misionpaz.ipynb
      - section: "Ecuador"
        contents:
          - text: "@_FamiliaEcuador"
            url: pages/familiaecuador.ipynb
          - text: "@etorrescobo"
            url: pages/etorrescobo.ipynb
          - text: "@MamelaFialloFlo"
            url: pages/mamelafialloflo.ipynb
  repo-url: https://github.com/DataCritica/capir-transfronteriza2-2023
  repo-actions: [edit, issue]
